antimicrobials = [
    { name = "Aminoglycosides", key = "AGS", type = "Aminoglycosides" },
    { name = "Amikacin", key = "AMI", type = "Aminoglycosides" },
    { name = "Dibekacin", key = "DIB", type = "Aminoglycosides" },
    { name = "Gentamicin", key = "GEN", type = "Aminoglycosides" },
    { name = "Kanamycin", key = "KAN", type = "Aminoglycosides" },
    { name = "Netilmicin", key = "NET", type = "Aminoglycosides" },
    { name = "Streptomycin", key = "STM", type = "Aminoglycosides" },
    { name = "Spectinomycin", key = "SPT", type = "Aminoglycosides" },
    { name = "Tobramycin", key = "TOB", type = "Aminoglycosides" },
    { name = "Beta-Lactams", key = "BLA", type = "Beta-Lactams" },
    { name = "Amoxicillin", key = "AMX", type = "Beta-Lactams" },
    { name = "Ampicillin", key = "AMP", type = "Beta-Lactams" },
    { name = "Methicillin", key = "MET", type = "Beta-Lactams" },
    { name = "Penicillin", key = "PEN", type = "Beta-Lactams" },
    { name = "Cefuroxime", key = "CXM", type = "Beta-lactams" },
    { name = "Cephalothin", key = "CET", type = "Beta-lactams" },
    { name = "Extended Spectrum Beta-Lactams", key = "ESBL", type = "Extended Spectrum Beta-Lactams" },
    { name = "Ceftazidime", key = "CAZ", type = "Extended Spectrum Beta-Lactams" },
    { name = "Cefepime", key = "FEP", type = "Extended Spectrum Beta-Lactams" },
    { name = "Ceftriaxone", key = "CRO", type = "Extended-Spectrum Beta-Lactams" },
    { name = "Capreomycin", key = "CAP", type = "Capreomycin" },
    { name = "Carbapenems", key = "CBP", type = "Carbapenems" },
    { name = "Ertepenem", key = "ETP", type = "Carbapenems" },
    { name = "Meropenem", key = "MEM", type = "Carbapenems" },
    { name = "Broad-Spectrum Cephalosporins", key = "CEP", type = "Broad-Spectrum Cephalosporins" },
    { name = "Cefixime", key = "CFM", type = "Broad-spectrum Cephalosporins" },
    { name = "Cefotaxime", key = "CTX", type = "Broad-spectrum Cephalosporins" },
    { name = "Colistin", key = "CST", type = "Colistin" },
    { name = "Co-Trimoxazole", key = "SXT", type = "Combination" },
    { name = "Amoxicillin-Clavulanic Acid", key = "AMC", type = "Combination" },
    { name = "Piperacillin-Tazobactam", key = "TZP", type = "Combination" },
    { name = "Quinupristin-Dalfopristin", key = "QDP", type = "Combination" },
    { name = "Antiseptic", key = "ANT", type = "Disinfectants/Antiseptics"},
    { name = "Trimethoprim", key = "TMP", type = "Diaminopyrimidine" },
    { name = "Fusidic Acid", key = "FUS", type = "Fusidic Acid" },
    { name = "Fluoroquinolones", key = "FLQ", type = "Fluoroquinolones" },
    { name = "Ciprofloxacin", key = "CIP", type = "Fluoroquinolones" },
    { name = "Moxifloxacin", key = "MFX", type = "Fluoroquinolones" },
    { name = "Nalidixic acid", key = "NAL", type = "Fluoroquinolones" },
    { name = "Teicoplanin", key = "TEC", type = "Glycopeptides" },
    { name = "Vancomycin", key = "VAN", type = "Glycopeptides" },
    { name = "Tigecycline", key = "TGC", type = "Glycylcycline" },
    { name = "Isoniazid", key = "ISH", type = "Isoniazid" },
    { name = "Clindamycin", key = "CLI", type = "Lincosamides" },
    { name = "Daptomycin", key = "DAP", type = "Lipopeptides" },
    { name = "Macrolides", key = "MAC", type = "Macrolides" },
    { name = "Azithromycin", key = "AZM", type = "Macrolides" },
    { name = "Clarithromycin", key = "CLR", type = "Macrolides" },
    { name = "Erythromycin", key = "ERY", type = "Macrolides" },
    { name = "Telithromycin", key = "TEL", type = "Macrolides" },
    { name = "Tylosin", key = "TYL", type = "Macrolides" },
    { name = "Mupirocin", key = "MUP", type = "Mupirocin" },
    { name = "Furazolidone", key = "FZL", type = "Nitrofurans" },
    { name = "Nitrofurantoin", key = "NFT", type = "Nitrofurans" },
    { name = "Linezolid", key = "LNZ", type = "Oxazolidinone" },
    { name = "Other", key = "SIL", type = "Other" },
    { name = "Chloramphenicol", key = "CHL", type = "Phenicols" },
    { name = "Florfenicol", key = "FFN", type = "Phenicols" },
    { name = "Fosfomycin", key = "FOF", type = "Phosphonic Acid" },
    { name = "Pyrazinamide", key = "PZA", type = "Pyrazinamide" },
    { name = "Rifampicin", key = "RIF", type = "Rifamycin" },
    { name = "Streptogramin A", key = "SGA", type = "Streptogramins" },
    { name = "Streptogramin B", key = "SGB", type = "Streptogramins" },
    { name = "Sulfonamides", key = "SMX", type = "Sulfonamides" },
    { name = "Sulfamethoxazole", key = "SSS", type = "Sulfonamides" },
    { name = "Sulfisoxazole", key = "SSX", type = "Sulfonamides" },
    { name = "Doxycycline", key = "DOX", type = "Tetracyclines" },
    { name = "Minocycline", key = "MIN", type = "Tetracyclines" },
    { name = "Tetracycline", key = "TCY", type = "Tetracyclines" },
    # Anti fungals
    { name = "5-flucytosine", key = "5FC", type = "5-flucytosine" },
    { name = "Anidulafungin", key = "AFG", type = "Anidulafungin" },
    { name = "Caspofungin", key = "CAS", type = "Caspofungin" },
    { name = "Fluconazole", key = "FLC", type = "Fluconazole" },
    { name = "Micafungin", key = "MFG", type = "Micafungin" }
]
